2021-03-06 14:58:11,133 ERROR: Exception on /user/admin [GET] [in /Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hoshingcheung/PycharmProjects/microblog_lab07/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/hoshingcheung/PycharmProjects/microblog_lab07/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/hoshingcheung/PycharmProjects/microblog_lab07/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/hoshingcheung/PycharmProjects/microblog_lab07/app/templates/user.html", line 17, in block "content"
    {{ form.hidden_tag() }}
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-03-06 15:07:09,064 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:07:48,810 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:09:03,226 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:09:19,500 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:10:49,380 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:11:01,501 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:11:51,793 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:15:31,756 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:17:56,153 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:19:09,970 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:23:21,431 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:27:30,667 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:27:44,695 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:27:48,341 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:28:01,551 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:28:58,222 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:29:05,137 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:47:08,033 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:47:58,117 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:48:32,899 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:48:52,794 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 15:50:54,292 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab07/app/__init__.py:44]
2021-03-06 16:16:12,765 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab08/app/__init__.py:44]
2021-03-06 19:12:49,855 INFO: Microblog startup [in /Users/hoshingcheung/PycharmProjects/microblog_lab09/app/__init__.py:45]
2021-03-06 19:13:22,879 ERROR: Exception on /reset_password_request [POST] [in /Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/hoshingcheung/PycharmProjects/microblog_lab09/app/routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "/Users/hoshingcheung/PycharmProjects/microblog_lab09/app/email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/hoshingcheung/PycharmProjects/microblog_lab09/app/models.py", line 65, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-03-06 19:13:41,014 ERROR: Exception on /reset_password_request [POST] [in /Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hoshingcheung/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/hoshingcheung/PycharmProjects/microblog_lab09/app/routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "/Users/hoshingcheung/PycharmProjects/microblog_lab09/app/email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/hoshingcheung/PycharmProjects/microblog_lab09/app/models.py", line 65, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
